cmd/chall-manager-janitor/main.go
webdocs/ops-guides/deployment/index.md

This PR solves #401 by introducing a ticker to the `chall-manager-janitor`.
Despite it remains not recommended to rely on the ticker but on an external cron, this enable Docker-based setups to use the janitor.

Add a ticker to the janitor

---

.gitignore
examples/no-sdk/README.md
examples/no-sdk/build.sh
examples/prebuilt/README.md
examples/prebuilt/build.sh
go.work.sum

This PR removes the binary artifacts we could find in the `examples/`.
It will solve the security alert on the subject, and improve further the example explanation by providing a way to reproduce it.

Remove binary artifacts

---

examples/exposed-monopod/main.go
sdk/kubernetes/exposed-monopod.go
webdocs/challmaker-guides/software-development-kit/index.md
webdocs/tutorials/a-complete-example/index.md

This PR solves the issue we encountered when working on the Hack'lantique 2025.
We were not able to create ingresses due to a lack of information : where is the ingress running ?
Due to no answers available, we could not build the `NetworkPolicy` that accepts traffic from the `IngressController` toward the challenge pods.
In this PR I solve this issue by adding two new parameters : `IngressNamespace` to give the namespace in which the `IngressController` is running, and `IngressLabels` to specify a pod in this namespace rather than every one of them.
At the end of the `provision` function, in the _exposure_ switch, I combine them to create the required `NetworkPolicy`.
It was the occasion to move around some specific code for NodePorts.
I update the webdoc to document those new infos …

Fix ingress exposure missing information for it to work

---

README.md

This PR adds the ICAISC25 event in the `README.md` list :confetti_ball: :tada:

Add ICAISC25 in events

---

api/v1/instance/renew.go

Hello there ! 
While working on ctfer-io/ctfd-chall-manager#107 I realized that the chall-manager API did not correctly handle the instance renewal request in the case where the challenge defined an `Until` and a `Timeout`. 
This PR remove the (useless) check before the `ComputeUntil` and return a custom message if the computed until is the same of the challenge one (this is mean even if the Players make a renewal request, CM will not update the until of their instances).

fix(instance): permit renew if both timeout and until is define

---

README.md

This PR adds Hack'lantique 2025 to the trophy list.

Add Hack'lantique 2025 to trophy list

---

.github/workflows/prs.yaml

This PR adds dependency review for PRs, to determine if there will be known vulnerabilities or restrictive licenses introduced in the PRs.

Add dependency review on PRs

---

.github/workflows/integration.yaml
.github/workflows/release.yaml

This PR pins dependencies in workflows and use `$(...)` rather than backticks, thanks to [octoscan](https://github.com/synacktiv/octoscan) report.

Improve security practices

---

deploy/services/parts/chall-manager.go

This PR adds the Pod Security Standard on the constructed namespace in which challenges are deployed.
See https://raw.githubusercontent.com/kubernetes/website/main/content/en/examples/security/podsecurity-baseline.yaml for labels origin.

Add Pod Security Standard baseline

---

sdk/kubernetes/exposed-multipod.go
sdk/kubernetes/kompose.go

This PR turns off default Kubernetes behavior of mounting the default ServiceAccount into pods. As this is not required (having a SA) and even if it can't be used to pivot thanks to NetworkPolicies, it opens room for potential exploitation when chained with a potential lack of control.
By disabling it, we do not affect the features of these SDK resources, but reinforce the security-by-default posture of the SDK.
Poke @TPGamesNL :)
Resolves #623

fix: disable service account auto-mount by default

---

api/v1/challenge/delete.go
api/v1/challenge/update.go
api/v1/common/metrics.go
api/v1/instance/create.go
api/v1/instance/delete.go
api/v1/instance/spin.go

This PR adds metric attributes for dashboards, especially for instances, as:
- `challenge` the ID of the challenge an instance ;
- `source` the ID of the source that requested an instance (might not be present for pooled instances) ;
- `pool` indicate whether the instance is being integrated in the pool.
Resolves #627

feat:add metrics attributes for dashboards

---

sdk/kubernetes/exposed-monopod_test.go

This PR simply fixes the image name used during tests. It changes nothing but will avoid our k9s to get full red when running tests locally x)

fix: image name

---

deploy/Pulumi.yaml
deploy/main.go
deploy/services/chall-manager.go
deploy/services/parts/chall-manager.go

This PR adds the capability to deploy a [Romeo environment](https://github.com/ctfer-io/romeo/tree/main/environment) to export coverage data, mostly for tests coverage purposes.
It the key `romeo-claim-name` is set to a non-empty value in the Pulumi stack, coverage export is automatically turned on and bound to the PVC claim name pointed out within the namespace.

feat: add romeo claim name mount for coverage export

---

pkg/lock/etcd.go

With this PR I suggest we modify something that has been **disturbing for quite a while** when deploying to production : `etcd` spams logs with unwanted warnings about things we do not need.
My _simple_ proposal is to pass it a `zap.NewNop` logger such that it logs to nowhere rather than the production logger.

fix: don't pass production logger to etcd

---

deploy/Pulumi.yaml
deploy/main.go
deploy/services/chall-manager.go
deploy/services/parts/chall-manager.go

This PR adds deployment requests and limits to Chall-Manager container. It defaults them to a low size such that common deployments does not suffer from outages from caching compilations consuming all resources on the node.
Resolves #678

impr: add requests and limits to deploy

---

examples/kubernetes/main.go
examples/teeworlds/main.go
go.work.sum

This PR adds missing netpols to the examples.
A mecanism should be put in place during acceptance test over the examples to ensure their reachability. Due to the various protocol nature and no acceptances yet (mostly for performances of GHA workflows) I don't consider it yet.
Nonetheless I'll test them one by one tomorrow just to make sure they are valid. Until then, I won't merge the branch even if CI is all green and approved.

fix(#744): add missing netpols to examples

---

.github/workflows/ci.yaml
.github/workflows/release.yaml
api/v1/challenge/challenge.proto
api/v1/common/common.proto
api/v1/instance/instance.proto
buf.yaml
go.work.sum

This PR adds buf linting for `.proto`files, with `MINIMAL` rules. I avoid `STANDARD` due to various rules I don't want to consider especially in naming (see `buf config ls-lint-rules` output).
It also publish the protos to the BSR (Buf Schema Registry) on releases.
To test things I [manually pushed protos](https://buf.build/ctfer-io/chall-manager).
Resolves #741

impr: add buf lint and publish on release

---

cmd/chall-manager-janitor/main.go
global/etcd.go
global/otel.go
pkg/otel/caller.go
pkg/services/etcd/manager.go

In this PR I propose to improve the OTel support by adding the `service.version` conventional attribute to the tracer.
I also would like to introduce the `caller.function` such that, in traces, we are aware of which function emitted the call.
This finds value when trying to understand from where a call has been issued from one microservice to an other.
I wrap both unaries and streams, and make them available for others who would like to rely on it too using `github.com/ctfer-io/chall-manager/pkg/otel` package.
It changes no behavior and has impact only when `tracing` is on.

impr(otel): component version and caller function name in traces

---

.github/workflows/ci.yaml

This PR ignores generated files from coverage report. Coveralls will report actual coverage for files we write and maintain.

fix(ci): ignore generated code from coverages count

---

cmd/chall-manager/main.go
deploy/Pulumi.yaml
deploy/services/parts/chall-manager.go
global/config.go
global/etcd.go
go.work.sum
pkg/lock/concurrency.go
server/healthcheck.go

Resolves #799
:rotating_light: **Breaking change** :rotating_light: on CLI flags and environment variables. The Pulumi stack is not impacted.

fix(#799): reduce lock kind alternatives

---

.github/workflows/ci.yaml
.github/workflows/release.yaml

This PR proposes to only run the CI (unit/e2e tests + lint) only when Go or proto files are modified. It also runs on workflow update (e.g. dependabot PRs) to ensure there are no sudden breaking changes (e.g. golangci-lint recently added a package name lint rule which suddenly broke CI).
It should boost up the PR review time, especially for documentation.
Finally I fix the version settings by removing the ldflags (relica) and directly use github context environments.

Run CI when required

---

deploy/main.go
deploy/services/chall-manager.go
deploy/services/parts/chall-manager.go

Re-add the capability to set environment variables (venv) for `chall-manager`.
In case of overlap, the provided venvs override existing ones.
This might be very helpful for #779 as we would be able to define things like `GOPROXY` for Go, or `PULUMI_PLUGIN_DOWNLOAD_URL_OVERRIDES` for Pulumi.
For now -at least- I don't explicitly specify them in the the stack configuration, and is kind of a shadow stack configuration attribute (+ it must be set per `--path` not per `--plaintext` so is not usable within the integration tests).
It could also be useful when deploying with sensitive systems credentials (e.g. a Proxmox API token), such that you avoid hardcoding them within _scenarios_.

impr(deploy): add k=v env map

---

sdk/kubernetes/exposeType.go
sdk/kubernetes/exposed-monopod.go
sdk/kubernetes/exposed-monopod_test.go
sdk/kubernetes/exposed-multipod.go
sdk/kubernetes/exposed-multipod_test.go
sdk/kubernetes/kompose.go
sdk/kubernetes/kompose_test.go
sdk/kubernetes/mocks_test.go
sdk/kubernetes/port.go
webdocs/tutorials/a-complete-example/index.md

This PR focuses on the `kubernetes` submodule of the SDK, and improves:
1. how are exposed the containers as per `Kompose`, `ExposedMonopod` and `ExposedMultipod`, with a new exposure possibility being `LoadBalancer`;
2. how the annotations are passed to the exposing resources.
To date, CTFer.io deployments focuses on on-premise infrastructure. With our current stack (MetalLB, Traefik and DNSMasq) we where able to handle all NodePorts/Ingresses and distribute it efficiently to players. It worked fine for up to 200 players in production (at least we didn't have the opportunity to test with more, and I don't see why it would not work -- except a possible nodeport exhaustion).
Now, with way larger infrastructure we are not able to handle on-premise and must migrate toward cloud providers. …

[SDK] Improve Kubernetes exposures and annotations

---

api/v1/challenge/update.go
go.work.sum
pkg/fs/challenge.go
pkg/scenario/oci.go
pkg/scenario/oci_test.go

Chall-Manager, before OCI support, was copying the scenario in its global directory leading to collocated scenarios and filesystem-based _DB_.
Nonetheless, what needs to be distributed among replicas is actually the filesystem-DB, not the scenario... thus it is bloating the duplicated data. Moreover, for shared scenarios (e.g. the [recipes](https://github.com/ctfer-io/recipes)), this data is duplicated. Finally, these scenarios are expected to be available to all replicas in a OCI registry, thus can be quickly pulled back whenever required.
These is clearly a replica we could **completly remove**.
This PR proposes the following layout:
- store the filesystem _DB_ in `/tmp/chall-manager` (actually I'll move it to `/etc/chall-manager` in an other PR, it makes no sense in `/tmp` as we should …

Move OCI scenarios into cache

---

cmd/chall-manager/main.go
global/cache.go
global/config.go
pkg/scenario/oci.go

Resolves #978
I add the `--cache` CLI flag and `CACHE` environment variable to configure the cache directory.
Is it now a global thing, used per the `pkg/scenario` under the `oci` sub-directory to be future-proof (if we ever want to cache other things it will be possible without conflicts with the current OCI stuff).
I don't consider adding this parametrisable per the `deploy` stack as this should not be a problem on Kubernetes. Assumption is based upon rationale that a local volume should not be a problem. I might come back on this idea later, e.g., when dealing with #977
Let me know if you consider this last point a limitation of the PR :wink:

feat(#978): configure cache directory
